language: node_js
branches:
  only:
  - source
node_js:
- '7'
before_install:
- rvm install 2.4.0
before_script:
- npm i -g gulp-cli
- npm install
- gem install bundler
- bundle install
script:
- gulp build-clean  --production
after_success:
- git clone https://$GITHUB_REPO
- git branch
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://user:${GH_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/neubias/neubias.github.io
  - REPO_TARGET_BRANCH: master
  - secure: bGOzunb0X7FwWIfGDVkGI2SNF2ZCpw1d0UZmIONK+q9H/ZfiomtXaMUDAVJpF7adgvDcXRU1OwjwBSr7aHpJY5jD7btLEBokYc1EMSlRJ+IoPUqUJL11iuXJFDfZL4ZK/Ck9KD7jspr0sphmNRCZr/8+DUw1KY3Tt5xlWPumb6RFV0lYCQtK74lL9zM6VI9lSPGpgPB6jAW6Ps31AM9n2Bc7BLJyrEbxygM95l++W5dPKzmAntjhjsgjZyW1FflCny3LgCLQF9Xy745oErKkhVec2DT8LBO7IwD2mp5LNs5jpFJK0cPggbHCOMXD5kdRX0yr8JUH8xTKtnYXd/bNgGigFojFRVoxacPwxWsLr2xZGgTul7qm1bEla0uVnTCKSgxue5T0jwkaxxWIHpkYYdRm+ZNRyy66WC+Pwp6acBs6FmWvMTVbhOa2fWjYJWT8sQzqG1QfWTqqaIx7mkt/gXcNFZh1IWqql0+q04agn4uO9eOpJvP/r8snGK9QjR0BlH0Wyqan5iXIzdfq2UFZm/ngFqNvb0S802n7o1qJ+KB/aAe1Fk9ZeCSstzz++Dju4R3sTaxnJ7Y9P41qVKo2M91B6g/92L+yLDfTLNrwicLD1Rdpl+hqCmbYReh23WvtwElLk6VDdhMY3otBJVFZFoEJcDIsnxUyUOxtjiJL9Jk=
  - secure: lHvKgXVPdY2+7ijlIRWgzva64rzo6alF+WNdTv6jJA1yP0d8P+XLACTYlEglRa+tBCOj+WdXvnO71zWcBsLv7ku7Fqg0OD062YzKjia5+L8PoklNj8+6AUR++RXaUp0PeXNozqkdWmuIyehG/DuW0I60eQOzTkNTlXw/+ObycL67xFyZ3nn8ao2Ibdf01qMVwcEee75OdNdvyFJYqRXFUhMxqdGvD14ytF7n5gITP/dbSKuo8Fg3pLbJGAh8k+PliDxNDq4GfBlQaUWyLwtu2F0vXpp0EBrmOK9GPGJO161bBONvf9O9xbUUNBikh1rfsIf5Jc8l+FLfWmhRtUA57rd7pHQxVj+sVy4wXGCKZNfsYe/ibvHS6Pv4J3nMITK4j5Db4Q5D+fDdxELuX5KWbBOz1co8cJtbno68mQso7QEjld3zj+OcdX6sVLzdAn9s+c/5YIv1VTEPT+KwghNy6KJDLvRy5Nbc7g7fCzAZRX2YJaMUaNAJ0txV+K5XFEO5kKS3R13HKLch7zktpw8UweHn32a2nOXm4lcFqgiTVCMAk/7pzLjCkm+gwWle/i5fvAaI6NnamsbZxXTOz+WRhdz6kmpvxn9LBB9u4OpC8wuShUHUlWF0Q0oYbmnpOyJNqxT/pKh82iEgetuGRbaC4ZuvTVnKWTmH2lEcLvxikwE=
