language: node_js
branches:
  only:
  - source
node_js:
- '7'
before_install:
- rvm install 2.4.0
before_script:
- npm i -g gulp-cli
- npm install
- gem install bundler
- bundle install
script:
- gulp build-clean  --production
after_success:
- git clone https://$GITHUB_REPO
- git branch
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://user:${GH_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/neubias/neubias.github.io
  - REPO_TARGET_BRANCH: master
  - secure: OwUI3yKavm8S6jS6RFgd6Z7SBEz9NVM7EiW5xIW7LXXaS2tlnPsY+5e9cdnuF8J866yAvOL1Qme3CNo6B84uNnU5+KzJuXYpZLdhxcNlVihace1TeXZ3Dbc0PsDli6f7OvfzI/wOD0/LlyoLGfT1HszMPpl13B0d283+mU0ff2DOsyZlS7m+tEvpNuYBZPrbwM/CbHbJXa7PViKWhs1S/VaAtlAG7+C+VRNlf8nv1tLFhuB7o0Kg3Vc+BiR4xZolXLZC7c2AKlO2juML1eiTQ4XRZJ+T/N+nMWN6PgamtlYaNBGO/PJEM1tmzCFrq1dzgGn6x3gCCOCVq0XGtMnU6eaZxrR/FbYpWzsJzlsm4SEh22T+THklcLIhF/NvxReFD5s02BUFbSvfiq55UcKXUk2pcCk4q9exL3kLftttLiJ2OcTwm/EMyqLZ0Al6p+y9BoyWudySz9jOSIudSV0zFj48I6AGMdxLNSFPJ1MJH/Plp7QbMs2dALDvfebZ/KDtjRgn/eGzsLvVJpdu7SzOKo/qFKDCFi9RA8HrjGAcwP6lbiVbkql4StRsLUO9uHq0Myj98qRfOj77evixTKySLzdedOoSWLZqgXNsm++BgVEwATuCJ7Dt3F20Nh26em+Vf6RENg5FQeHBsDA/62HEoIddseiRuWno8eujGTq3YL8=
  - secure: O4uK7/0EhCiqqbLGby8H7RkLKoHs3CyWfYxh+aL5ce/JvnQ88IKc53Ty4xgIOJltZ2GUHfamkrcQrUYiPPMQ7ZBDxydyGW8/XxqZYxML73woZcWlJnWl3X4BYxc7jhFB9MboPSFEayWmHP8m+zCciVykkTBLFcJvGsdT7PXEB9elgQJOynmTghbCoBcKAzbW4ZYznareROgbuuGkq9R27jI/7ATTcI6SVicwPyJnwQTTymHE34/Re0Z0X1pbqPhDTCttm+67x8YutSITJSO8DQUbIUB0buZoY+SsEqh8z6+mXAqsF1O+zrMHLSR+QurgATLhzOdcBVh0DZPH9BGSQqWNSeCsAVYfjl5tlqibblMyTPjLLtnxf1Hw6orMqcj0KSfWfHjRXkgzBQ/d6LkpSy+8hYZgBUERHpkiDRUvlJgvBmBBKcWuHG9GsCoXuUJAQt22DpgMfQwz+ItrgPQt/YSSenuVCbQSkv4Oj5mMAwqQbBKE8SYRb/20F6+Dccbnhfizsk5pzWMS+g1dND46W62x1YndnvABa2ZU2muudzQG2RTJFU5JAxCaa37DfOu3d7o+TV6+aMj89Vf8XpM6Kq1zi/OYxYMVQoqUzWsYTtytxAO5AXsaMKhfiQwbsUWXSN4OMpNgXDDs6lW0J551C52kGL/T6Y8HPoqFjdFFLE4=
