title: NeuBias Blog
email: caldas.victor@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The blog of the Network of European Bio Image Analysts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vcaldasv
github_username:  vcaldas

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate


# Build settings
markdown: kramdown
paginate: 5
paginate_path: 'page:num/'
comments: true
excerpt_separator: <!-- more -->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - examples
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

